// @generated by tools/sync-shared.ts from plugins/dev-core/skills/shared/workflows/workflows.ts — DO NOT EDIT. Run: bun run sync:shared

/**
 * @deprecated Prefer `workflow-generators` (pure) or `workflow-push` (I/O).
 * Re-exports pure generators only — no push I/O, no github-adapter edge.
 */
export * from './workflow-generators'
