"""Tests for the shared-sources-sync check in tools/validate_plugins.py."""

import importlib.util
import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOL = REPO_ROOT / 'tools' / 'validate_plugins.py'


def run_tool(*extra_args):
    """Run validate_plugins.py as a subprocess and return (returncode, stdout, stderr)."""
    result = subprocess.run(
        [sys.executable, str(TOOL), *extra_args],
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout, result.stderr


def _load_module():
    """Load validate_plugins module via importlib so injected paths work."""
    spec = importlib.util.spec_from_file_location('validate_plugins', TOOL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture()
def repo_scratch():
    """Yield a unique scratch directory inside REPO_ROOT; remove it on teardown.

    Files created here have paths that are relative to REPO_ROOT, so the
    is_relative_to(REPO_ROOT) guard in check_shared_sources_sync passes cleanly.
    """
    scratch = REPO_ROOT / 'tests' / '_scratch_shared_sources' / uuid.uuid4().hex
    scratch.mkdir(parents=True, exist_ok=True)
    try:
        yield scratch
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _rel(path: Path) -> str:
    """Return a REPO_ROOT-relative path string for a file inside repo_scratch."""
    return str(path.relative_to(REPO_ROOT))


# Source of truth for this prefix: tools/sync-shared.ts::makeHeader()
# Real header shape: `// @generated by tools/sync-shared.ts from <canonicalPath> — DO NOT EDIT. Run: bun run sync:shared`
# The strip in check_shared_sources_sync is line-count-based (lines[2:]), so the `from <path>`
# segment doesn't affect stripping behaviour — but keeping the prefix aligned avoids latent divergence.
_GENERATED_HEADER_PREFIX = '// @generated by tools/sync-shared.ts'


def _make_generated_target(canonical_content: str, canonical_path: str = 'plugins/dev-core/skills/shared/config-helpers.ts') -> str:
    """Wrap canonical_content with the 2-line @generated header expected by the byte-equality loop.

    Mirrors tools/sync-shared.ts::makeHeader() which produces:
      // @generated by tools/sync-shared.ts from <canonicalPath> — DO NOT EDIT. Run: bun run sync:shared
    """
    header = f'{_GENERATED_HEADER_PREFIX} from {canonical_path} — DO NOT EDIT. Run: bun run sync:shared'
    return f'{header}\n\n{canonical_content}'


def _write_manifest_and_files(scratch: Path, entries: list[dict], manifest_name: str = 'shared-sources.json') -> Path:
    """Write a shared-sources.json manifest inside *scratch* and the referenced files.

    Each entry dict has keys: 'canonical_sub' (str, relative to scratch), 'target_sub'
    (str, relative to scratch), 'content' (str).

    The manifest stores REPO_ROOT-relative path strings so the is_relative_to guard passes.
    Both canonical and target files are created with byte-equal content (target gets the
    @generated header) so the byte-equality loop in check_shared_sources_sync passes cleanly.
    """
    manifest = []
    for e in entries:
        canonical_abs = scratch / e['canonical_sub']
        target_abs = scratch / e['target_sub']
        content: str = e['content']

        canonical_abs.parent.mkdir(parents=True, exist_ok=True)
        canonical_abs.write_text(content, encoding='utf-8')

        target_abs.parent.mkdir(parents=True, exist_ok=True)
        target_abs.write_text(_make_generated_target(content), encoding='utf-8')

        manifest.append({
            'canonical': _rel(canonical_abs),
            'targets': [_rel(target_abs)],
        })

    manifest_file = scratch / manifest_name
    manifest_file.write_text(json.dumps(manifest), encoding='utf-8')
    return manifest_file


def _write_biome(scratch: Path, includes: list[str], name: str = 'biome.json') -> Path:
    """Write a minimal biome.json with overrides[0].includes set to *includes*."""
    biome = {
        'overrides': [
            {'includes': includes}
        ]
    }
    biome_file = scratch / name
    biome_file.write_text(json.dumps(biome), encoding='utf-8')
    return biome_file


# ---------------------------------------------------------------------------
# Happy path — current repo state must be in sync
# ---------------------------------------------------------------------------

def test_current_repo_in_sync():
    """Running --check shared-sources-sync against the actual repo must exit 0."""
    rc, stdout, stderr = run_tool('--check', 'shared-sources-sync')
    assert rc == 0, (
        'validate_plugins.py --check shared-sources-sync reports drift on current HEAD.\n'
        f'stderr:\n{stderr}\nstdout:\n{stdout}'
    )


# ---------------------------------------------------------------------------
# IO path: biome.json absent — must return non-empty errors containing 'not found at'
# ---------------------------------------------------------------------------

def test_biome_absent_returns_io_error(repo_scratch):
    """When biome.json does not exist, check returns an IO error naming the missing path."""
    # Arrange — valid manifest with byte-equal canonical/target so the byte-equality loop is clean
    manifest_file = _write_manifest_and_files(repo_scratch, [
        {'canonical_sub': 'src/a.ts', 'target_sub': 'dist/a.ts', 'content': 'export const a = 1\n'},
    ])

    bogus_biome = repo_scratch / 'does-not-exist' / 'biome.json'
    # Do NOT create the file — we want the not-found IO path

    # Act
    mod = _load_module()
    errors = mod.check_shared_sources_sync(manifest_path=manifest_file, biome_path=bogus_biome)

    # Assert — errors must be non-empty and name the missing path
    assert errors, 'Expected an IO error when biome.json is absent'
    combined = '\n'.join(errors)
    assert 'not found at' in combined, f"Expected 'not found at' in error output, got: {combined}"
    assert str(bogus_biome) in combined, f'Expected the bogus path in error output, got: {combined}'


# ---------------------------------------------------------------------------
# Mismatch: manifest target absent from biome includes
# ---------------------------------------------------------------------------

def test_biome_missing_manifest_target(repo_scratch):
    """When biome includes omits a manifest target, check returns error naming the target."""
    # Arrange — two manifest entries; biome omits target_b
    manifest_file = _write_manifest_and_files(repo_scratch, [
        {'canonical_sub': 'src/a.ts', 'target_sub': 'dist/a.ts', 'content': 'export const a = 1\n'},
        {'canonical_sub': 'src/b.ts', 'target_sub': 'dist/b.ts', 'content': 'export const b = 2\n'},
    ])

    target_a_rel = _rel(repo_scratch / 'dist' / 'a.ts')
    target_b_rel = _rel(repo_scratch / 'dist' / 'b.ts')

    # biome includes only target_a — target_b is missing
    biome_file = _write_biome(repo_scratch, [target_a_rel])

    # _copy_sync_prefix: scratch targets live under tests/_scratch_shared_sources/<uuid>/dist/
    # — pass the scratch-relative prefix so the override-locator finds the right override.
    scratch_prefix = _rel(repo_scratch) + '/'

    # Act
    mod = _load_module()
    errors = mod.check_shared_sources_sync(
        manifest_path=manifest_file, biome_path=biome_file, _copy_sync_prefix=scratch_prefix
    )

    # Assert
    assert errors, 'Expected errors when a manifest target is missing from biome includes'
    combined = '\n'.join(errors)
    assert 'missing copy-sync target' in combined
    assert target_b_rel in combined
    # target_a is legitimately present — must NOT be flagged
    assert target_a_rel not in combined


# ---------------------------------------------------------------------------
# Mismatch: biome includes an extra path not in manifest targets
# ---------------------------------------------------------------------------

def test_biome_extra_non_manifest_entry(repo_scratch):
    """When biome includes an extra path absent from manifest targets, check reports it."""
    # Arrange — single manifest entry; biome adds a phantom extra path
    manifest_file = _write_manifest_and_files(repo_scratch, [
        {'canonical_sub': 'src/a.ts', 'target_sub': 'dist/a.ts', 'content': 'export const a = 1\n'},
    ])

    target_a_rel = _rel(repo_scratch / 'dist' / 'a.ts')
    phantom_rel = _rel(repo_scratch / 'dist' / 'phantom.ts')

    biome_file = _write_biome(repo_scratch, [target_a_rel, phantom_rel])

    # _copy_sync_prefix: scratch targets live under tests/_scratch_shared_sources/<uuid>/dist/
    # — pass the scratch-relative prefix so the override-locator finds the right override.
    scratch_prefix = _rel(repo_scratch) + '/'

    # Act
    mod = _load_module()
    errors = mod.check_shared_sources_sync(
        manifest_path=manifest_file, biome_path=biome_file, _copy_sync_prefix=scratch_prefix
    )

    # Assert
    assert errors, 'Expected errors when biome includes a non-manifest entry'
    combined = '\n'.join(errors)
    assert 'non-manifest entry' in combined
    assert phantom_rel in combined
    # target_a is legitimately present — must NOT be flagged
    assert target_a_rel not in combined


# ---------------------------------------------------------------------------
# Clean state: biome includes == manifest targets (set-equal, byte-clean)
# ---------------------------------------------------------------------------

def test_biome_equals_manifest_no_drift(repo_scratch):
    """When biome includes is set-equal to manifest targets and all copies are synced, errors are empty."""
    # Arrange — two manifest entries; biome includes exactly those two targets
    manifest_file = _write_manifest_and_files(repo_scratch, [
        {'canonical_sub': 'src/a.ts', 'target_sub': 'dist/a.ts', 'content': 'export const a = 1\n'},
        {'canonical_sub': 'src/b.ts', 'target_sub': 'dist/b.ts', 'content': 'export const b = 2\n'},
    ])

    target_a_rel = _rel(repo_scratch / 'dist' / 'a.ts')
    target_b_rel = _rel(repo_scratch / 'dist' / 'b.ts')

    # biome includes exactly the two targets — set-equal, no extra, no missing
    biome_file = _write_biome(repo_scratch, [target_a_rel, target_b_rel])

    # _copy_sync_prefix: scratch targets live under tests/_scratch_shared_sources/<uuid>/dist/
    # — pass the scratch-relative prefix so the override-locator finds the right override.
    scratch_prefix = _rel(repo_scratch) + '/'

    # Act
    mod = _load_module()
    errors = mod.check_shared_sources_sync(
        manifest_path=manifest_file, biome_path=biome_file, _copy_sync_prefix=scratch_prefix
    )

    # Assert
    assert errors == [], (
        f'Expected no errors when biome includes matches manifest targets exactly.\n'
        f'Got: {errors}'
    )
