// @generated by tools/sync-shared.ts from plugins/dev-core/skills/shared/adapters/env-config.ts — DO NOT EDIT. Run: bun run sync:shared

/**
 * EnvConfigAdapter — concrete ConfigPort backed by process.env.
 */

import type { ConfigPort } from '../ports/config'
import { detectGitHubRepo, resolvePriority, resolveSize, resolveStatus } from './config-helpers'

export class EnvConfigAdapter implements ConfigPort {
  getRepo(): string {
    return detectGitHubRepo()
  }

  resolveStatus(input: string): string | undefined {
    return resolveStatus(input)
  }

  resolvePriority(input: string): string | undefined {
    return resolvePriority(input)
  }

  resolveSize(input: string): string | undefined {
    return resolveSize(input)
  }
}
