// @generated by tools/sync-shared.ts from plugins/dev-core/skills/shared/lefthook-persist.ts — DO NOT EDIT. Run: bun run sync:shared

/**
 * Lefthook persist detect — lefthook binds the canonical freeze script.
 * Presence of the string `check-principal-branch.sh` (comment / one hook) is not persist.
 */

export const PRINCIPAL_FREEZE_SCRIPT = 'check-principal-branch.sh'
export const PRINCIPAL_FREEZE_RUN = `bash scripts/${PRINCIPAL_FREEZE_SCRIPT}`

export function lefthookTopLevelSectionBody(yaml: string, section: string): string | null {
  const header = new RegExp(`^${section}:\\s*$`, 'm')
  const m = header.exec(yaml)
  if (!m) return null
  const start = m.index + m[0].length
  const rest = yaml.slice(start)
  const nextTop = rest.search(/^\S/m)
  return nextTop === -1 ? rest : rest.slice(0, nextTop)
}

function uncommentedLines(body: string): string[] {
  return body.split('\n').filter((line) => !/^\s*#/.test(line))
}

function runValueBindsScript(raw: string): boolean {
  const val = raw.replace(/^run:\s*/, '').replace(/^['"]|['"]$/g, '')
  return val.includes(PRINCIPAL_FREEZE_SCRIPT)
}

/** True iff lefthook will invoke check-principal-branch.sh under this hook's `commands:`. */
export function lefthookSectionBindsPrincipalFreeze(yaml: string, section: string): boolean {
  const body = lefthookTopLevelSectionBody(yaml, section)
  if (body === null) return false
  let inCommands = false
  let inFreeze = false
  let commandsIndent = -1
  let freezeIndent = -1
  for (const line of uncommentedLines(body)) {
    const indent = (line.match(/^[ \t]*/)?.[0] ?? '').length
    const trimmed = line.trim()
    if (!trimmed) continue
    if (!inCommands) {
      if (/^commands:\s*$/.test(trimmed)) {
        inCommands = true
        commandsIndent = indent
      }
      continue
    }
    if (indent <= commandsIndent) {
      inCommands = false
      inFreeze = false
      if (/^commands:\s*$/.test(trimmed)) {
        inCommands = true
        commandsIndent = indent
      }
      continue
    }
    if (inFreeze && indent <= freezeIndent) {
      inFreeze = false
    }
    if (/^principal-freeze:\s*$/.test(trimmed) && indent > commandsIndent) {
      inFreeze = true
      freezeIndent = indent
      continue
    }
    if (inFreeze && indent > freezeIndent && /^run:\s*\S/.test(trimmed) && runValueBindsScript(trimmed)) {
      return true
    }
  }
  return false
}

/** Persist lefthook.yml: both pre-commit and pre-push bind the canonical script. */
export function lefthookHasPrincipalFreeze(yaml: string): boolean {
  return (
    lefthookSectionBindsPrincipalFreeze(yaml, 'pre-commit') && lefthookSectionBindsPrincipalFreeze(yaml, 'pre-push')
  )
}

export function lefthookSectionHasPrincipalFreezeKey(yaml: string, section: string): boolean {
  const body = lefthookTopLevelSectionBody(yaml, section)
  if (body === null) return false
  return uncommentedLines(body).some((line) => /^\s*principal-freeze:\s*$/.test(line))
}

export function preCommitHasPrincipalFreeze(yaml: string): boolean {
  const lines = uncommentedLines(yaml)
  const hasId = lines.some(
    (line) => /^\s*-\s+id:\s*principal-freeze\s*$/.test(line) || /^\s*id:\s*principal-freeze\s*$/.test(line),
  )
  const hasEntry = lines.some((line) => {
    const trimmed = line.trim()
    if (!/^entry:\s*/.test(trimmed)) return false
    return trimmed.includes(PRINCIPAL_FREEZE_SCRIPT)
  })
  return hasId && hasEntry
}
