// @generated by tools/sync-shared.ts from plugins/dev-core/skills/shared/ports/workspace.ts — DO NOT EDIT. Run: bun run sync:shared

/**
 * WorkspacePort — role interface for workspace/worktree/git operations.
 */
import type { Branch, Worktree } from '../domain/types'

export interface VercelProjectRef {
  projectId: string
  teamId: string
}

export interface WorkspaceProject {
  repo: string
  label: string
  type?: 'technical' | 'company'
  vercelProjectId?: string // single Vercel project ID (legacy / single-project)
  vercelTeamId?: string // Vercel team ID for single project
  vercelProjects?: VercelProjectRef[]
  localPath?: string
}

export type ProjectType = 'technical' | 'company'

export interface Workspace {
  projects: WorkspaceProject[]
}

export interface WorkspacePort {
  readWorkspace(): Workspace
  writeWorkspace(ws: Workspace): void
  listBranches(): Promise<Branch[]>
  listWorktrees(): Promise<Worktree[]>
}
