#!/usr/bin/env bash
set -euo pipefail
# provision-release-gate.sh — the two-part gate provisioner (#353, S12 / D6 / D15).
#
# Makes the `release-consistency` gate REAL (not advisory) on a target repo, and
# is the exact thing /promote step 1 (S7) probes for. Two artifacts, one script:
#
#   (a) commits the per-repo caller stub `.github/workflows/release-consistency.yml`
#       into the TARGET repo (heredoc-rendered). The stub carries the TRIGGERS
#       (pull_request/push/workflow_dispatch) — a reusable workflow's own
#       non-workflow_call triggers fire in its HOST repo, never in the caller
#       (D15), so the triggers must live in a committed per-repo stub. The stub's
#       single job is named `release-consistency`, byte-for-byte equal to the
#       reusable workflow's job name (T11) — that name IS the required-check
#       context (D15, S7/S12 agree byte-for-byte).
#
#   (b) creates a `main`-targeting branch ruleset REQUIRING the
#       `release-consistency` check-run context with ZERO bypass actors (a
#       bypassable required check is advisory with better marketing — edge case).
#
# Idempotent: a clean re-run makes no change (blob-sha compare for the stub,
# name lookup for the ruleset). `--remove` reverses BOTH — deletes the stub
# commit and the ruleset.
#
# NOTE ON THE FILENAME COLLISION: the caller stub and the reusable workflow share
# the basename `release-consistency.yml` but live in different repos (stub in the
# target repo, reusable in Roxabi/roxabi-plugins). That is intentional and fine.
#
# ORDER MATTERS: the stub is committed BEFORE the ruleset is created. Reversing
# the order would arm a required status check on a branch that has no workflow
# reporting it → the branch deadlocks before the stub can land.
#
# Every mutation goes through `gh api` / `gh`. Nothing here runs until invoked;
# the file is `bash -n`-clean and safe to inspect without touching the live org.

# ── constants (do NOT drift from T11) ────────────────────────────────────────
STUB_PATH=".github/workflows/release-consistency.yml"
JOB_NAME="release-consistency"          # == reusable workflow job name == required context (D15)
RULESET_NAME="release-consistency-gate" # ruleset object name (distinct from PR_Main)
REUSABLE="Roxabi/roxabi-plugins/.github/workflows/release-consistency.yml"
COMMIT_BRANCH="main"                    # the gate lives on main: the ruleset targets refs/heads/main
                                        # and pull_request(base=main) reads the workflow from main.
DEFAULT_REF="roxabi-plugins/v0.5.0"     # reusable-workflow pin; a tag, not a branch — `staging`
                                        # no longer exists and a moving branch is not a safe pin

usage() {
  cat >&2 <<'USAGE'
Usage: provision-release-gate.sh <owner/repo> [--ref <git-ref>] [--remove]

  <owner/repo>   target repo (a bare name is prefixed with the Roxabi org)
  --ref <ref>    reusable-workflow pin in the stub's `uses:` (default:
                 roxabi-plugins/v0.5.0 — always pin to a tag, never a branch)
  --remove       reverse BOTH artifacts: delete the caller stub and the ruleset

Provisions (idempotent):
  1. commit .github/workflows/release-consistency.yml (caller stub) to main
  2. create a main-targeting ruleset requiring the `release-consistency`
     check-run context with ZERO bypass actors
USAGE
  exit "${1:-2}"
}

# ── arg parsing ──────────────────────────────────────────────────────────────
REPO=""
REF="$DEFAULT_REF"
REMOVE=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --ref)
      [ "$#" -ge 2 ] || { echo "error: --ref needs an argument" >&2; usage 2; }
      REF="$2"; shift 2 ;;
    --ref=*)  REF="${1#--ref=}"; shift ;;
    --remove) REMOVE=1; shift ;;
    -h|--help) usage 0 ;;
    -*) echo "error: unknown flag '$1'" >&2; usage 2 ;;
    *)
      [ -z "$REPO" ] || { echo "error: unexpected extra argument '$1'" >&2; usage 2; }
      REPO="$1"; shift ;;
  esac
done

[ -n "$REPO" ] || { echo "error: target repo is required" >&2; usage 2; }
# bare name → default org
case "$REPO" in */*) : ;; *) REPO="Roxabi/${REPO}" ;; esac

# ── preflight ────────────────────────────────────────────────────────────────
for bin in gh jq git base64; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: '$bin' is required but not found" >&2; exit 3; }
done

# ── stub renderer ────────────────────────────────────────────────────────────
# Quoted heredoc: no bash expansion, so GitHub `${{ ... }}` expressions survive
# verbatim. The reusable-workflow ref is the ONLY dynamic field — injected by a
# single sed against the `@__REF__` sentinel on the `uses:` line.
render_stub() {
  local ref=$1
  sed "s|@__REF__|@${ref}|" <<'YAML'
# Caller stub — release-consistency gate (#353, S9b / D15).
# GENERATED by scripts/provision-release-gate.sh in Roxabi/roxabi-plugins.
#
# This thin per-repo stub carries the TRIGGERS. A reusable workflow's own
# non-workflow_call triggers fire in its HOST repo, never in the caller (D15),
# so pull_request/push/workflow_dispatch MUST live here. The single job's NAME
# (release-consistency) is the required-check context the main ruleset requires
# and /promote step 1 (S7) probes for — keep it byte-identical to the reusable
# workflow's job name.
name: release-consistency

# Quoted so YAML 1.1 does not coerce the `on` key to boolean true.
"on":
  pull_request:
    branches: [main]
    # `edited` is required: the PR title is a witness (D9) and editing a title
    # fires no other event. `synchronize` re-prices per head SHA on mid-review
    # pushes (D6).
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version_files_override:
        description: >-
          JSON/YAML list of version-file paths to check on the push/dispatch
          path, overriding release.version_files (S10 verification). Passed
          straight through to the reusable workflow.
        type: string
        required: false

permissions:
  contents: read

jobs:
  # Job name == required-check context. Do NOT rename without updating the
  # ruleset context (provision-release-gate.sh) and /promote's step-1 probe in
  # lockstep (D15).
  release-consistency:
    uses: Roxabi/roxabi-plugins/.github/workflows/release-consistency.yml@__REF__
    with:
      # Null on pull_request/push (coerces to ""); the reusable workflow treats
      # an empty override as "use release.version_files".
      version_files_override: ${{ inputs.version_files_override }}
YAML
}

# ── remote helpers ───────────────────────────────────────────────────────────
# Blob sha GitHub stores for the stub path on COMMIT_BRANCH ("" if absent).
remote_stub_sha() {
  gh api "repos/${REPO}/contents/${STUB_PATH}?ref=${COMMIT_BRANCH}" --jq '.sha' 2>/dev/null || true
}

# Ruleset id by name ("" if none).
ruleset_id() {
  gh api "repos/${REPO}/rulesets" \
    --jq ".[] | select(.name == \"${RULESET_NAME}\") | .id" 2>/dev/null | head -n1 || true
}

# ── provision (a): caller stub ───────────────────────────────────────────────
provision_stub() {
  local tmp local_sha remote_sha content
  tmp=$(mktemp)
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN
  render_stub "$REF" > "$tmp"

  local_sha=$(git hash-object "$tmp")   # == the git blob sha GitHub stores
  remote_sha=$(remote_stub_sha)

  if [ "$local_sha" = "$remote_sha" ]; then
    echo "stub: up to date (${STUB_PATH}@${COMMIT_BRANCH}, ref=${REF}) — no change"
    return 0
  fi

  content=$(base64 -w0 "$tmp")
  local -a args=(
    "repos/${REPO}/contents/${STUB_PATH}" --method PUT
    -f "message=chore: provision release-consistency gate stub (#353)"
    -f "content=${content}"
    -f "branch=${COMMIT_BRANCH}"
  )
  # Updating an existing file requires its current blob sha.
  [ -n "$remote_sha" ] && args+=(-f "sha=${remote_sha}")

  gh api "${args[@]}" >/dev/null
  if [ -n "$remote_sha" ]; then
    echo "stub: updated ${STUB_PATH}@${COMMIT_BRANCH} (ref=${REF})"
  else
    echo "stub: created ${STUB_PATH}@${COMMIT_BRANCH} (ref=${REF})"
  fi
}

# ── provision (b): main-targeting ruleset ────────────────────────────────────
provision_ruleset() {
  local id body
  id=$(ruleset_id)
  if [ -n "$id" ]; then
    echo "ruleset: '${RULESET_NAME}' already present (id=${id}) — no change"
    return 0
  fi

  # ZERO bypass actors (empty list) — a bypassable required check is advisory.
  body=$(jq -n \
    --arg name "$RULESET_NAME" \
    --arg ctx "$JOB_NAME" \
    '{
      name: $name,
      target: "branch",
      enforcement: "active",
      conditions: { ref_name: { include: ["refs/heads/main"], exclude: [] } },
      rules: [
        {
          type: "required_status_checks",
          parameters: {
            strict_required_status_checks_policy: false,
            required_status_checks: [ { context: $ctx } ]
          }
        }
      ],
      bypass_actors: []
    }')

  printf '%s' "$body" | gh api "repos/${REPO}/rulesets" --method POST --input - >/dev/null
  echo "ruleset: created '${RULESET_NAME}' — requires '${JOB_NAME}' on main, zero bypass actors"
}

# ── remove: reverse BOTH ─────────────────────────────────────────────────────
remove_stub() {
  local remote_sha
  remote_sha=$(remote_stub_sha)
  if [ -z "$remote_sha" ]; then
    echo "stub: ${STUB_PATH}@${COMMIT_BRANCH} absent — no change"
    return 0
  fi
  gh api "repos/${REPO}/contents/${STUB_PATH}" --method DELETE \
    -f "message=chore: remove release-consistency gate stub (#353)" \
    -f "sha=${remote_sha}" \
    -f "branch=${COMMIT_BRANCH}" >/dev/null
  echo "stub: removed ${STUB_PATH}@${COMMIT_BRANCH}"
}

remove_ruleset() {
  local id
  id=$(ruleset_id)
  if [ -z "$id" ]; then
    echo "ruleset: '${RULESET_NAME}' absent — no change"
    return 0
  fi
  gh api "repos/${REPO}/rulesets/${id}" --method DELETE >/dev/null
  echo "ruleset: removed '${RULESET_NAME}' (id=${id})"
}

# ── main ─────────────────────────────────────────────────────────────────────
if [ "$REMOVE" -eq 1 ]; then
  echo "== removing release-consistency gate on ${REPO} =="
  # Reverse order of provisioning: drop the ruleset first (so the required check
  # stops blocking), then delete the stub.
  remove_ruleset
  remove_stub
  echo "== done =="
else
  echo "== provisioning release-consistency gate on ${REPO} (ref=${REF}) =="
  provision_stub      # (a) — must land before the ruleset arms the required check
  provision_ruleset   # (b)
  echo "== done =="
fi
