#!/usr/bin/env bun

/**
 * Sync shared source files from canonical to all targets.
 *
 * Usage:
 *   bun run tools/sync-shared.ts           — write all targets
 *   bun run tools/sync-shared.ts --check   — verify targets match; exit 1 if drifted
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, sep } from 'node:path'

interface SharedEntry {
  canonical: string
  targets: string[]
}

const REPO_ROOT = resolve(import.meta.dir, '..')
const MANIFEST_PATH = resolve(REPO_ROOT, 'tools/shared-sources.json')

const manifest: SharedEntry[] = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'))

function makeHeader(canonicalPath: string): string {
  return `// @generated by tools/sync-shared.ts from ${canonicalPath} — DO NOT EDIT. Run: bun run sync:shared\n\n`
}

function buildGenerated(canonicalPath: string, canonicalContent: string): string {
  return makeHeader(canonicalPath) + canonicalContent
}

function assertInRepo(abs: string, rel: string): void {
  if (abs !== REPO_ROOT && !abs.startsWith(REPO_ROOT + sep)) {
    throw new Error(`Refusing path outside repo: ${rel}`)
  }
}

const checkMode = process.argv.includes('--check')

let drifted = false

for (const entry of manifest) {
  const canonicalAbs = resolve(REPO_ROOT, entry.canonical)
  assertInRepo(canonicalAbs, entry.canonical)
  const canonicalContent = readFileSync(canonicalAbs, 'utf-8')
  const expected = buildGenerated(entry.canonical, canonicalContent)
  const normalized = expected.replace(/\r\n/g, '\n')

  for (const target of entry.targets) {
    const targetAbs = resolve(REPO_ROOT, target)
    assertInRepo(targetAbs, target)

    if (checkMode) {
      if (!existsSync(targetAbs)) {
        console.error(`DRIFT: ${target} is missing. Run: bun run sync:shared`)
        drifted = true
        continue
      }
      const actual = readFileSync(targetAbs, 'utf-8')
      if (actual !== normalized) {
        console.error(`DRIFT: ${target} is out of sync with ${entry.canonical}. Run: bun run sync:shared`)
        drifted = true
      }
    } else {
      writeFileSync(targetAbs, normalized, { encoding: 'utf-8' })
      console.log(`synced: ${target}`)
    }
  }
}

if (checkMode) {
  if (drifted) {
    process.exit(1)
  } else {
    console.log('All shared sources are in sync.')
    process.exit(0)
  }
}
