#!/usr/bin/env bun

/**
 * Sync shared source files from canonical to all targets.
 *
 * Usage:
 *   bun run tools/sync-shared.ts           — write all targets
 *   bun run tools/sync-shared.ts --check   — verify targets match; exit 1 if drifted
 */

import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs'
import { dirname, resolve, sep } from 'node:path'

interface SharedEntry {
  canonical: string
  targets: string[]
}

const REPO_ROOT = resolve(import.meta.dir, '..')
const MANIFEST_PATH = resolve(REPO_ROOT, 'tools/shared-sources.json')

const manifest: SharedEntry[] = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'))

// HEADER CONTRACT: makeHeader emits exactly 2 lines (line 1 = @generated
// comment, line 2 = blank). tools/validate_plugins.py::check_shared_sources_sync
// strips these same 2 lines (lines[2:]) before byte-comparing. Keep both sides
// in lockstep — changing the header shape/length here must update the Python strip.
function makeHeader(canonicalPath: string): string {
  return `// @generated by tools/sync-shared.ts from ${canonicalPath} — DO NOT EDIT. Run: bun run sync:shared\n\n`
}

function buildGenerated(canonicalPath: string, canonicalContent: string): string {
  return makeHeader(canonicalPath) + canonicalContent
}

function assertInRepo(abs: string, rel: string): void {
  let real = abs
  try {
    real = realpathSync(abs)
  } catch (e) {
    // Only a genuine ENOENT (path not yet written) falls back to the lexical abs;
    // a non-Error throw or any other errno (ELOOP, EACCES, …) must rethrow.
    if (!(e instanceof Error) || (e as NodeJS.ErrnoException).code !== 'ENOENT') throw e
  }
  if (real !== REPO_ROOT && !real.startsWith(REPO_ROOT + sep)) {
    throw new Error(`Refusing path outside repo: ${rel}`)
  }
}

const checkMode = process.argv.includes('--check')

let drifted = false

for (const entry of manifest) {
  const canonicalAbs = resolve(REPO_ROOT, entry.canonical)
  assertInRepo(canonicalAbs, entry.canonical)
  const canonicalContent = readFileSync(canonicalAbs, 'utf-8')
  const expected = buildGenerated(entry.canonical, canonicalContent)
  const normalized = expected.replace(/\r\n/g, '\n')

  for (const target of entry.targets) {
    const targetAbs = resolve(REPO_ROOT, target)
    assertInRepo(targetAbs, target)

    if (checkMode) {
      if (!existsSync(targetAbs)) {
        console.error(`DRIFT: ${target} is missing. Run: bun run sync:shared`)
        drifted = true
        continue
      }
      const actual = readFileSync(targetAbs, 'utf-8')
      if (actual !== normalized) {
        console.error(`DRIFT: ${target} is out of sync with ${entry.canonical}. Run: bun run sync:shared`)
        drifted = true
      }
    } else {
      // writeFileSync does not create parent dirs — a target in a brand-new shared
      // subdir would otherwise crash ENOENT on its first sync.
      mkdirSync(dirname(targetAbs), { recursive: true })
      writeFileSync(targetAbs, normalized, { encoding: 'utf-8' })
      console.log(`synced: ${target}`)
    }
  }
}

if (checkMode) {
  if (drifted) {
    process.exit(1)
  } else {
    console.log('All shared sources are in sync.')
    process.exit(0)
  }
}
